spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://eventflow-postgres:5432/eventflow
    username: eventflow
    password: eventflow
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: notification_schema
    open-in-view: false
  flyway:
    schemas: notification_schema
    default-schema: notification_schema
  kafka:
    bootstrap-servers: eventflow-kafka:9092
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
    producer:
      properties:
        spring.json.add.type.headers: true

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
