spring:
  application:
    name: audit-service
  datasource:
    url: jdbc:postgresql://localhost:5433/eventflow
    username: eventflow
    password: eventflow
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: audit_schema
    open-in-view: false
  flyway:
    schemas: audit_schema
    default-schema: audit_schema
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: audit-service
      auto-offset-reset: earliest

eventflow:
  audit:
    simulation:
      fail-on-event-type:

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: audit-service

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} [service=${spring.application.name}, correlationId=%X{correlationId}, eventId=%X{eventId}, orderId=%X{orderId}] - %msg%n"
