spring:
  application:
    name: payment-service
  kafka:
    bootstrap-servers: eventflow-kafka:9092
    consumer:
      group-id: payment-service
      auto-offset-reset: earliest
    producer:
      properties:
        spring.json.add.type.headers: false
  datasource:
    url: jdbc:postgresql://eventflow-postgres:5432/eventflow
    username: eventflow
    password: eventflow
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: payment_schema
    open-in-view: false
  flyway:
    schemas: payment_schema
    default-schema: payment_schema

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info
