spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5433/eventflow
    username: eventflow
    password: eventflow
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: order_schema
    open-in-view: false
  flyway:
    schemas: order_schema
    default-schema: order_schema
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      properties:
        spring.json.add.type.headers: false

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: order-service

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

eventflow:
  outbox:
    publisher:
      enabled: true
      fixed-delay: 5000
      batch-size: 20
      max-retries: 3

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} [service=${spring.application.name}, correlationId=%X{correlationId}, eventId=%X{eventId}, orderId=%X{orderId}] - %msg%n"
