spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5433/eventflow
    username: eventflow
    password: eventflow
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: order_schema
    open-in-view: false
  flyway:
    schemas: order_schema
    default-schema: order_schema
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      properties:
        spring.json.add.type.headers: false

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
